# frozen_string_literal: true

# Load SolidQueue tables into the primary database.
# Generated by `rails solid_queue:install` — the queue_schema.rb is
# intended for a separate queue database, but StreamVault uses a
# single database so we load the tables here.
class CreateSolidQueueTables < ActiveRecord::Migration[8.1]
  def up
    # Only create if the tables don't already exist
    return if connection.table_exists?("solid_queue_jobs")

    eval(File.read(Rails.root.join("db/queue_schema.rb")))
  end

  def down
    # Don't drop — SolidQueue tables are managed by the gem
  end
end
